
name: 🚀 Deploy music.real6.ml
on:
  workflow_run:
    workflows: ["生成静态文件"]
    branches: [main]
    types: 
      - completed

jobs:
  web-deploy:
    name: 🎉 Deploy 部署到music.real6.ml
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://iuweb.ueuo.com
        ftp-username: iuweb.ueuo.com
        ftp-password: ${{ secrets.ftp_password }}
