
on:
  push:
    branches: [ gh-pages ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://music.real6.ml
        ftp-username: music.real6.ml
        ftp-password: ${{ secrets.ftp_password }}
